### ISSUE TITLE
Support for yarn@>=2.0.0

### ISSUE THREAD

**Issue by andrew-codes** [microsoft/ado-npm-auth#4]
Since yarn >=2.0.0, yarn no longer uses or respects either the `.npmrc` file or `.yarnrc`. Instead, it stores its configuration in a YAML file, `~/.yarnrc.yml`. Supporting an streamlined way to obtain necessary authentication for Azure DevOps registry feeds for yarn@>=2.0.0 would be greatly appreciated.

**Comment by andrew-codes** [comment]
I am willing to try this and open a PR. I wanted to verify first if it would be accepted and if there are any items I should be aware of to contribute. I do not see a contributor's guide, so I thought I would ask prior to doing any work. Thanks!

**Comment by jcreamer898** [comment]
If you're down for it, please feel free to give it a try!

**Comment by brwai** [comment]
Hi, any updates on this issue? I'm also running into this problem when trying to adopt yarn 4. Currently have to workaround with solution mentioned here: https://github.com/yarnpkg/berry/issues/316#issuecomment-1165605882 It would be great if we can use this tool to improve dev experience! Happy to contribute to help as well if needed :)
