### ISSUE TITLE
`azureauth` bin not found

### ISSUE THREAD

**Issue by jonchurch** [microsoft/ado-npm-auth#42]
**Describe the bug**
Looks like the `bin` didn't ship in v0.5.1 of `azureauth`

**To Reproduce**
```sh
npm exec azureauth@0.5.1 -- --version
# sh: azureauth: command not found
```

Compare to

```sh
npm exec azureauth@0.4.7 -- --version
# 0.8.4.0
```

For v5.0.1 we have in package.json:
```json
  "bin": {
    "azureauth": "./bin/cli.js"
  },

```

But the tarball we get has:
```sh
ls node_modules/azureauth
LICENSE.txt  README.md    dist         package.json scripts
```

**Comment by jonchurch** [comment]
Guessing it regressed here: https://github.com/microsoft/ado-npm-auth/commit/5d5c5cdc2b98bfbcbd29fcad19054255544c30c0

When the executable was moved into a `.gitignore`d dir, which will be ignored by `npm publish`

**Comment by dannyvv** [comment]
@jonchurch : Working on a fix... I should have included the file in the `files` section...

**Comment by dannyvv** [comment]
ado-npm-auth 0.1.11  and azureauth 0.11.0 should have the fix.
