### ISSUE TITLE
Package scoped registries are not recognized

### ISSUE THREAD

**Issue by codysorgenfrey** [microsoft/ado-npm-auth#52]
**Describe the bug**
Tool fails to recognize package scoped registries in project `.npmrc`.
 
**To Reproduce**
1. Create a packaged scoped entry in `/.npmrc`. (ex. `@somescope:registry=https...`)
2. Run `npm exec ado-npm-auth`
3. See error `Error: Registry URL missing or invalid`
4. Remove scope (ex. `registry=https...`)
5. Run  `npm exec ado-npm-auth`
6. See success `✅ Current authentication is valid`

**Expected behavior**
I would expect the tool to refresh my ado token for the given registry even if it is package scoped.

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2
 - Browser Edge 132.0.2953.0 (Official build) canary (64-bit)

**Comment by dannyvv** [comment]
Thank you @codysorgenfrey for reporting this.

I found the issue in the code. It goes wrong inside package `@npmcli/config` in file `lib/index.js`
```js
 process.emit('time', 'config:load:credentials')
    const reg = this.get('registry')
    const creds = this.getCredentialsByURI(reg)
    // ignore this error because a failed set will strip out anything that
    // might be a security hazard, which was the intention.
    try {
      this.setCredentialsByURI(reg, creds)
    // eslint-disable-next-line no-empty
    } catch (_) {}
    process.emit('timeEnd', 'config:load:credentials')
```

It assumes that the `.npmrc` file has a `registry` field.
If you add a global registry to the .npmrc file it will work.

```
@somescope:registry=https://some...
registry=https://other...
```
We are using an ancient version of the package. (4.2.2) I'll have a peek to see if we can update and if that will address the issue.

**Comment by codysorgenfrey** [comment]
This fixed the issue for anyone looking in the future.
