### ISSUE TITLE
Broken Screenshot on npm Page

### ISSUE THREAD

**Issue by Stuart-Wilcox** [microsoft/ado-npm-auth#7]
The screenshot on the [npm page](https://www.npmjs.com/package/ado-npm-auth) is broken and shows only the helper text

![image](https://github.com/microsoft/ado-npm-auth/assets/22772721/a751c8d8-e0bb-4963-8450-1be3c6641bfe)

**Comment by jcreamer898** [comment]
haha, I actually noticed that too, it's fixed as of 0.0.3.
